from PIL import Image, ImageDraw, ImageFont, ImageOps
import textwrap

def create_polaroid(user_image, text, language="English"):
    """
    製作 IG 黃金比例 (4:5) 的拍立得美圖 - 修復版
    """
    
    # 1. 設定畫布
    CANVAS_WIDTH = 1080
    CANVAS_HEIGHT = 1350
    SIDE_PADDING = 60
    TOP_PADDING = 60
    BOTTOM_AREA = 380
    
    target_img_width = CANVAS_WIDTH - (SIDE_PADDING * 2)
    target_img_height = CANVAS_HEIGHT - TOP_PADDING - BOTTOM_AREA
    
    # 2. 智慧裁切
    resized_img = ImageOps.fit(
        user_image, 
        (target_img_width, target_img_height),
        method=Image.Resampling.LANCZOS,
        centering=(0.5, 0.5)
    )
    
    # 3. 建立畫布
    canvas = Image.new('RGB', (CANVAS_WIDTH, CANVAS_HEIGHT), '#FDFDFD')
    canvas.paste(resized_img, (SIDE_PADDING, TOP_PADDING))
    
    # 4. 準備寫字
    draw = ImageDraw.Draw(canvas)
    
    if "Thai" in language:
        font_path = "assets/font_th.ttf"
        font_size = 65 
        line_spacing = 30
        wrap_width = 30
    else:
        font_path = "assets/font_tc.ttf"
        font_size = 58
        line_spacing = 25
        wrap_width = 22
        
    try:
        font = ImageFont.truetype(font_path, font_size)
        logo_font = ImageFont.truetype(font_path, 28)
    except:
        font = ImageFont.load_default()
        logo_font = ImageFont.load_default()
        print("⚠️ 找不到字型")

    text_color = "#222222"
    
    wrapper = textwrap.TextWrapper(width=wrap_width) 
    word_list = wrapper.wrap(text=text) 
    wrapped_text = '\n'.join(word_list)
    
    bbox = draw.textbbox((0, 0), wrapped_text, font=font, align="center")
    text_width = bbox[2] - bbox[0]
    text_height = bbox[3] - bbox[1]
    
    text_x = (CANVAS_WIDTH - text_width) / 2
    
    text_area_start_y = TOP_PADDING + target_img_height
    text_area_center_y = text_area_start_y + (BOTTOM_AREA / 2)
    text_y = text_area_center_y - (text_height / 2) - 20
    
    draw.multiline_text(
        (text_x, text_y), 
        wrapped_text, 
        fill=text_color, 
        font=font, 
        align="center",
        spacing=line_spacing
    )
    
    # Logo
    logo_text = "Generated by PetOS"
    logo_bbox = draw.textbbox((0, 0), logo_text, font=logo_font)
    logo_width = logo_bbox[2] - logo_bbox[0]
    logo_x = (CANVAS_WIDTH - logo_width) / 2
    logo_y = CANVAS_HEIGHT - 60
    
    draw.text((logo_x, logo_y), logo_text, fill="#AAAAAA", font=logo_font)

    # --- 關鍵！一定要把成品交出去 ---
    return canvas